apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:

helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: gatus-1.5.0
    releaseName: gatus
    valuesFile: values.yaml
    namespace: observability